name: Ingest Embeddings

on:
  push:
    paths:
      - 'content/**'
  workflow_dispatch:
    inputs:
      content_path:
        description: 'Path to content files'
        required: false
        default: 'content/'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai supabase tiktoken pypdf docx2txt python-pptx pytesseract pillow
      - name: Run ingestion script
        run: pnpm ingest:content
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CONTENT_PATH: ${{ github.event.inputs.content_path || 'content/' }}
